### PR TITLE
Feature/menu component

### PR DESCRIPTION
**Pull request by groundfloorwebb**
Fixes #
Ports Buefy's menu component to oruga and provides a refactored version for Vue 3

### CODE REVIEW

**Comment by groundfloorwebb** [comment]
Yeah it's still a draft, Vue 3 is next on my agenda. I wanted to make sure I could get a working build with Vue 2 before I moved on.

**Comment by jtommy** [comment]
@groundfloorwebb sure, take your time!

**Comment by groundfloorwebb** [comment]
@jtommy ready for review

**Review by jtommy — CHANGES_REQUESTED** [review]
A first quick review

**Comment by groundfloorwebb** [comment]
@jtommy implemented your requested changes, have another look.

**Review by jtommy — APPROVED** [review]

**Comment by jtommy** [comment]
@groundfloorwebb just found out the inspector and class props are totally missing 😞 Also the UI is not really good, can you take a look at the default theme? Thanks

**Pull request merged**
