### PR TITLE
Feature/promise for notifications and loading

### PR DESCRIPTION
**Pull request by urkle**
## Proposed Changes

- add the programmatic "promise" contract from modal to the notification component
- add the programmatic "promise" contract from modal to the loading component
- fix some bugs in the Vue 3 programmatic loading component

### CODE REVIEW

**Comment by urkle** [comment]
@jtommy thanks for processing these PRs so quickly.

- Do you have an ETA on when you'll cut a new release?
- you need to update your project as there are now some completed items in that list that can be moved to done ( https://github.com/oruga-ui/oruga/projects/1 )
- Is there any other tasks you would want me to help knock out?

**Comment by jtommy** [comment]
There are things that I wanted to fix before to make a new release, probably next week.

I merged your PR but to be honest i'm not sure about programmatic and promise prop but it works 😄 

There are a lot of things to do 😃

**Comment by urkle** [comment]
> There are things that I wanted to fix before to make a new release, probably next week.

OK

> There are a lot of things to do 😃

Yes, there are :)    I myself am using this in 3 different projects now. One that I started w/ Beufy and am transitioning it to Oruga, and two others that are in Oruga, one in Vue 2 and one in Vue 3. (slowly working toward migrating things to Vue 3 everywhere). 

So, anything you need help with building out I can do so. You can even just create an issue and assign it to me in github.

**Comment by jtommy** [comment]
> > There are things that I wanted to fix before to make a new release, probably next week.
> 
> OK
> 
> > There are a lot of things to do 😃
> 
> Yes, there are :) I myself am using this in 3 different projects now. One that I started w/ Beufy and am transitioning it to Oruga, and two others that are in Oruga, one in Vue 2 and one in Vue 3. (slowly working toward migrating things to Vue 3 everywhere).
> 
> So, anything you need help with building out I can do so. You can even just create an issue and assign it to me in github.

Ok thanks! No rush but I've just assigned a issue

**Pull request merged**
