### PR TITLE
feat(types): added better typescript support using vue-tsc d.ts generation

### LINKED ISSUE #263: Improve typescript support for vue 3 (oruga-next)
### Description

Currently oruga has a very basic typescript support, provided by [this](https://github.com/oruga-ui/oruga/blob/208dd47e88002fb6f9cc55f6d194bb9f8f84eb13/packages/oruga-next/types/index.d.ts#L1) unique line, this only avoids that IDE's and typescript diagnostics trigger errors.
 
 
### Posible start point
To provide a more complete and native typescript support can be used `vue-tsc` to generate a very complete definitions for each component, like its described [here](https://github.com/johnsoncodehk/volar/tree/master/packages/vue-tsc#using), this can be used as is, or can be handily improved over specific use cases.

### Why Oruga need this feature

To Improve Developer Experience (DX) and the lib quality. Many modern Vue projects are now using typescript as their base. and workspaces like `Volar + VsCode` are focused in strongly typed components. 
this can also help more developers how are switching from Vue 2 environments like `Buefy` or others, to choose oruga.

### PR DESCRIPTION
**Pull request by D4RKAR117**
Fixes #263 

## Proposed Changes

- Added d.ts automatic generation using vue-tsc for vue component, mixins and directives using `npm run build:types`
- Added better vue type checking using new script `npm run lint:typings`
- Added initial `oruga-next` complex type definitions

### Side notes
The commands `build:types` and `lint:typings` will end with `exit code 1` at the moment due, context injections wrong resolves and other behaviors that escapes the `tsc proxies` (that vue tsc are using) scopes. Some of the errors that are reported by the proxy get solved removing `shims-vue.d.ts` from the context,  but not all of them are solved. **So this errors are more informative than actually indicators for test proposes or problems by themselves**. 

Also removing `shims-vue.d.ts` gives to non prepared workspaces to not found `.vue` files. so its recommended that for  future development proposes, `oruga-next` adopts volar takeover mode as is explained [here](https://github.com/johnsoncodehk/volar/discussions/471).

### Recommendations

For CI/CD proposes due the limitations of the `vue-tsc` explained above. its recommended that the type generation and type checking related tasks get executed in a `allowed to fail` stage or a manual approach before each actual build stage.

### CODE REVIEW

**Comment by jtommy** [comment]
@D4RKAR117 Awesome!! I'm going to test all as soon as possible in order to include it in the next release.

About CI/CD @astagi is more experienced than me, surely he'll find a good solution!

**Comment by D4RKAR117** [comment]
That's good to hear, I'll try to improve typescript support in general for Vue 3, starting with trying to remove "any" definitions from project types. But I think it will be after the next release.

**Comment by jtommy** [comment]
@D4RKAR117 did you test it in a real project?

Anyway, there are some problems with programmatic components (probably the most important types of the library), for example modal. Also useProgrammatic type is not well defined, for example `const { oruga } = useProgrammatic();`.

Please test it a project to know the real needs using the library

**Comment by D4RKAR117** [comment]
Yeah i tested it in a local project of mine, but not too much in deep. i will check programmatic issues and i will try to solve them then. thanks for the feedback, so i think that this need to be marked as a draft WIP.

**Comment by jtommy** [comment]
@D4RKAR117 any news?

**Comment by D4RKAR117** [comment]
Unfortunately, I still haven't been able to dedicate time to improve the typing due to my work. As soon as I have any progress I will share it.

**Comment by D4RKAR117** [comment]
@jtommy hey, i'm slowly advancing in typing's for `oruga-next`, i turned off  the `any` rule of typescript to improve as much as posible the types and trying to solve many of any references posible, but i have some doubts:

- As i describe [here](https://discord.com/channels/743963673529286656/930150756680626247/946961813348692038) in discord, i have some troubles typing one of the directives, `clickOutside`. so some guidance over that directive is appreciated
- I found that many of the components such as `Table`, are written with options api, so this limits in some ways, like `provide / inject` type assertions or props acknowledge between components, so, can i rewrite them in composition api and `script setup ways` ? this can help in many ways, also adopting the new vue "preferred" way to do things for readability can help in some sort for future contributions i think. So let me know about what do you think about that.

**Comment by jtommy** [comment]
> @jtommy hey, i'm slowly advancing in typing's for `oruga-next`, i turned off the `any` rule of typescript to improve as much as posible the types and trying to solve many of any references posible, but i have some doubts:
> 
> * As i describe [here](https://discord.com/channels/743963673529286656/930150756680626247/946961813348692038) in discord, i have some troubles typing one of the directives, `clickOutside`. so some guidance over that directive is appreciated
> * I found that many of the components such as `Table`, are written with options api, so this limits in some ways, like `provide / inject` type assertions or props acknowledge between components, so, can i rewrite them in composition api and `script setup ways` ? this can help in many ways, also adopting the new vue "preferred" way to do things for readability can help in some sort for future contributions i think. So let me know about what do you think about that.
> * Also i want to know how is the recommended way to test all of the component use cases, at the moment I'm using a local project to review changes in DX and IDE assertion, but this is slow and inefficient, so if you had any advice of how to improve the oruga work flow is also appreciated

1. I should take a look to understand better
2. We are going to use it and refactor components but we need to reuse unit test from Vue 2 code. It's too dangerous operation at the moment
3. I don't know to be honest, at the moment the high priority is about programmatic components.

**Pull request closed without merging**
