### PR TITLE
docs: update active text color in theme dropdown

### PR DESCRIPTION
**Pull request by TerrniTLLC**
## Proposed Changes

- Changed the text color of the active element to make it prettier 

Before:
Screenshot_20240324_163624
After: 
Screenshot_20240324_163638

### CODE REVIEW

**Comment by mlmoravek** [comment]
Maybe its more a theme problem?

**Comment by TerrniTLLC** [comment]
I checked in google and firefox as well as on my mobile browser. Everywhere I look there is black text on the element when it is active. It's a small change, but I think it looks better this way

**Comment by mlmoravek** [comment]
Yes, but maybe it should be set as default by the theme?

**Comment by mlmoravek** [comment]
Ahh, I see what the problem is. Thank you @TerrniTLLC :)

**Pull request merged**
