### PR TITLE
Feature/close all notifications

### LINKED ISSUE #322: Close all shown toasts/notifications
### Description

Ability to close all shown toasts/notifications.

### Why Oruga need this feature

Useful when route changes. Clear page from all shown toasts/notifications when route changed.

### PR DESCRIPTION
**Pull request by urkle**
Fixes #322 

## Proposed Changes

- adds a $oruga.notifications.closeAll() method that will close all programmatic notifications

### CODE REVIEW

**Comment by urkle** [comment]
@jtommy should we also extend this concept to programmatic modals and loading components?

**Comment by jtommy** [comment]
> @jtommy should we also extend this concept to programmatic modals and loading components?

Yes

I'm reviewing the PR, programmatic component looks like a container of any thing 😄 
Btw why don't you add the instance into index.ts/.is in the open method?

**Comment by urkle** [comment]
> > should we also extend this concept to programmatic modals and loading components?
> 
> Yes
OK.. I'll build a followup PR to this one that adds it to those as well.

> I'm reviewing the PR, programmatic component looks like a container of any thing 😄 
Yea, basically.  If all we needed was a "truthy" to determine if we are programmatic, why add more properties for setting the extra data needed for extra functionality. Just change programmatic to be an object :)

> Btw why don't you add the instance into index.ts/.is in the open method?
So, yeah I could have done that in there.. but it felt "wrong" to have index add it and the component remove it.  It felt better to let the component add and remove itself instead so it was the only one responsible.

**Comment by jtommy** [comment]
@urkle does it ready to review?

**Comment by jtommy** [comment]
@urkle did you try it using individual imports? For example importing only notification and modal and not all Oruga bundle?

**Comment by urkle** [comment]
@jtommy I just did that right now importing just the pieces and injecting them like so
```javascript
  createApp(App)
    .use(Modal)
    .use(Button)
    .use(Notification)
    .use(Loading)
    .use(Config, bulmaConfig) // load theme
    .mount('#app');
```

Also calling closeAll on the imported NotificationProgrammatic module works as well.

**Pull request merged**
