### PR TITLE
Autocomplete oruga/next

### PR DESCRIPTION
**Pull request by smastrom-dolly**
Hello, I made some edits to the Autocomplete component, please let me know what you think and in case you're willing to merge I'll write the tests cases, make any eventual change/fix and restore the dev env as I found it. 

### 1. Unfiltered data displayed before clearing the field

<details><summary><strong>Video Current</strong></summary>

https://user-images.githubusercontent.com/78644132/218284342-e9a16f94-d9fd-424d-a23c-d15726602abe.mov

</details>

<details><summary><strong>Video PR</strong></summary>

https://user-images.githubusercontent.com/78644132/218284621-0d06abb1-5e0b-4a3b-be1e-2e9202cf3d62.mov

</details>

---

### 2. Dynamic menu positioning

I noticed that:

- The menu was not repositioning when scrolling but only when resizing:

<details><summary><strong>Video Current</strong></summary>

https://user-images.githubusercontent.com/78644132/218284860-df29ba49-f951-40df-a604-647aa9f81419.mov

</details>

- On resize, it was a bit flashy when repositioning (at least on Firefox):

<details><summary><strong>Video Current</strong></summary>

https://user-images.githubusercontent.com/78644132/218285113-e99b2b91-daf9-42b4-90d1-acd7cdf8a92a.mov

</details>

- Also repositioning on scroll/resize if the input is not scrolled by the window was not implemented.

I replaced the methods in charge of positioning when `menuPosition === 'auto'` with a single one named `setMenuAutoPosition` which works for both window and container scroll and also for `appendToBody`. User doesn't need to define the scrolling container as I wrote a tiny function which automatically detects it.

A [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) is initialized if the scrolling element is different than the window, if not window:onresize listener is init. I've also added new scroll listeners.

If user has set `appendToBody` the dropdown will be dynamically positioned on scroll/resize as well. This works when the input is scrolled by the window. If not, this won't have any effect as it won't be possible to hide/show it properly when the input overflows. I used [Vue Teleport](https://vuejs.org/guide/built-ins/teleport.html) for this feature. I simply added a condition which if the appendToBody is false or the scrolling element is not the documentElement it will disable the teleport and viceversa.

Basically now, user gets full dynamic positioning on scroll/resize wheter it is scrolled by the window or a container:

<details><summary><strong>Window Scroll - PR</strong></summary>

https://user-images.githubusercontent.com/78644132/218285683-28e6b84d-8789-4908-ad5c-fa997141ceb3.mov

</details>

<details><summary><strong>Custom Scroll Element - PR</strong></summary>

https://user-images.githubusercontent.com/78644132/218285744-75b9e4e7-b4ca-4b93-a0ba-d6e24b6c6d31.mov

</details>

<details><summary><strong>Window Resize - PR</strong></summary>

https://user-images.githubusercontent.com/78644132/218285776-f564b2e3-3691-48a0-a2ba-031701476a15.mov

</details>

<details><summary><strong>Custom Continer Resize - PR</strong></summary>

https://user-images.githubusercontent.com/78644132/218285837-47e7b874-f09d-4649-9fbe-d743b888ff85.mov

</details>

<details><summary><strong>Append to body - PR</strong></summary>

https://user-images.githubusercontent.com/78644132/218286019-051a9087-a790-47b8-a226-df3d0da62d83.mov

</details>

### CODE REVIEW

**Comment by jtommy** [comment]
@smastrom thanks for the PR, it contains a lot of improvements 🎉 

I know Vue Teleport and it's a great feature that i wanted to add to rewrite appendToBody feature.
Oruga is CSS agnostic but what happens using Teleport? Bulma, Bootstrap css contains classes that depends on parent, for example menu depends on its wrapper.

**Comment by smastrom** [comment]
As far as I can see the node `o-acp__menu` is teleported but as you pointed me things might be more complex.

The dropdown shares with the input the node `o-acp` which is also the parent of the input field and most likely this is the parent selector you're referring to.

From a dev perspective I would say, the moment I opt-in to `appendToBody` I'd also fully embrace the risks that it brings, for example the tab-index order.

Of course, it is possible to detect if it's using BS/Bulma and if necessary flush inline the styles it relies on (if they're just variables) or dynamically wrap the teleported dropdown in a parent which retains only the styles needed but this sounds to me out of scope as we're mutating too much the client's DOM.

The most senseful thing would be to leave things as they are, if the dev chooses to opt-in to `appendToBody` it will have to add manually the styles they want to retain.

**Comment by jtommy** [comment]
@smastrom why?

**Comment by smastrom** [comment]
I was cleaning up my profile forks but GitHub eventually also closed the PR. However, you might reopen it and resume from where I left.

**Comment by mlmoravek** [comment]
@smastrom-dolly I'm currently implementing a teleport alternative to appendToBody. I will aggnolage your suggested changes and add some inspired implementation to the dropdown component (autocomplete will now use the dropdown component internally).
I appreciate your work and feel free to have a look when the feature is released and suggest further changes.

**Pull request closed without merging**
