### PR TITLE
fix: wrong full page class name in Loading

### PR DESCRIPTION
**Pull request by levirs565**
## Proposed Changes

- Rename `fullPageIconClass` to `fullPageClass` in Loading component documentation
- Change `fullPageClass` description

### CODE REVIEW

**Comment by jtommy** [comment]
The docs is auto-generated running docs script and It reads props from component https://github.com/oruga-ui/oruga/blob/develop/packages/oruga/src/components/loading/Loading.vue

Please add the missing prop `fullPageClass` and run docs build. The markdown will be updated.

**Comment by levirs565** [comment]
I have been rename `fullPageIconClass` to `fullPageClass` in `loading/Inspector.vue`. This PR is ready now.

**Comment by jtommy** [comment]
Ok but you are missing to add `fullPageClass` prop to Loading.vue component (oruga and oruga-next) as I told you.

**Comment by jtommy** [comment]
Thanks 👍

**Pull request merged**
