### PR TITLE
Add tests command to CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by astagi**
Add tests command to CONTRIBUTING.md

### CODE REVIEW

**Comment by service-paradis** [comment]
I have a proposal. Instead of moving into the core package, we could add some script in the root `package.json`. Someting along:
```
    "test:oruga": "lerna run test --scope oruga",
    "test:all": "lerna run test --stream",
```
This way, it would be possible to test the package directly at the root using `npm run test:oruga`. It could be used to build also.

**Comment by jtommy** [comment]
@service-paradis it's a good idea

**Comment by jtommy** [comment]
@astagi can you work on it ? :)

**Comment by astagi** [comment]
@service-paradis sounds great! @jtommy I'll take care of that, np!

**Comment by astagi** [comment]
Closing in favour of #21

**Pull request closed without merging**
